### ISSUE TITLE
Having trouble creating external ingress for prod

### ISSUE THREAD

**Issue by AndyUM357** [ACloudGuru-Resources/Course_Practical_Guide_EKS#24]
Chapter 5: Creation of the Production Environment - Part 2
Course_Practical_Guide_EKS/Infrastructure/helm-charts/central-ingress
Creating the 2 prod load balancers, I get the internal one but the external one is not created in EC2, also get some warnings:
```
$ ./create.sh prod
W1112 15:25:21.793656    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1112 15:25:21.824321    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1112 15:25:21.861043    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1112 15:25:21.975333    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1112 15:25:22.006066    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1112 15:25:22.045948    1400 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Release "central-ingress-prod" has been upgraded. Happy Helming!
NAME: central-ingress-prod
LAST DEPLOYED: Fri Nov 12 15:25:21 2021
NAMESPACE: prod
STATUS: deployed
REVISION: 5
TEST SUITE: None
```
```
$ kubectl get ingresses -n prod
NAME                       CLASS    HOSTS                                                                                             ADDRESS
                                                           PORTS   AGE
central-ingress-external   <none>   bookstore.x.com,api.x.com
                                                           80      57m
central-ingress-internal   <none>   renting-api.x.com,resource-api.x.com,inventory-api.x.com + 1 more...   internal-1xe8c3d1-prod-centralingre-9e08-xx.us-east-2.elb.amazonaws.com   80      57m
```
Is there something I need to update?  No external ALB and the central-ingress-external doesn't get an ADDRESS either.  Any help appreciated - thx

**Comment by mariomerco** [comment]
Hey @AndyUM357, thanks for following the course!

So two things:
1. The warnings doesn't matter right now. EKS doesn't support v1.22 of Kubernetes **YET**, but it will, so for now we are fine. Either way, since we are using the AWS Load Balancer Controller, it doesn't support other apiVersion of the _Ingress_ than _extensions/v1beta1_. So in short, don't worry about it. For more information about the lack of support of the new version of the apiVersion of ingress, please visit this: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2050 (I'm watching this to update the source code of the code once this is supported 😉)

2. Regarding the not creation of your load balancer, please check the logs of the _AWS load balancer controller_ pod:
```
kubectl get pods -n kube-system
```
Get the **pod-id** and then run
```
kubectl logs -n kube-system <pod-id>
```

Those logs might give you an idea.

**Now**, sometimes this happens because the VPC is not correctly set for Kubernetes to discover the subnets, and it cannot find the Internet Facing subnets, so I invite you to visit the Subnet Discovery documentation of the controller and **pay special attention to the tags**: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/subnet_discovery/

**Comment by AndyUM357** [comment]
Thanks Mario!  Yes, it appears the subnet discovery is an issue when I look at the albingress-controller logs:
`E1112 20:45:26.850324       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/eks-acg': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"prod","Name":"central-ingress-external"}`

**Comment by mariomerco** [comment]
It should work after you configure those tags like that in the curresponding Internet facing subnets. If it doesn't create the LB immediatelly, delete the Helm Release `central-ingress-prod` and create it again (better than deleting and manually creating the ingress).

**Comment by AndyUM357** [comment]
Thank you, it works!  Looks like I didn't have the {"kubernetes.io/cluster/eks-acg" | "shared"} tag on my public subnets.  Appreciate the help -- great course!

**Comment by mariomerco** [comment]
Keep being awesome!!
